language: node_js

sudo: false

node_js:
  - node

os:
  - linux

matrix:
  include:
    - os: osx
      env: COMPILER=clang++
      osx_image: xcode9.4
      compiler: clang
    - os: linux
      env: CXX=clang
      compiler: clang

branches:
  only:
    - master

deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
