image: Visual Studio 2015

environment:
  NODEJS_VERSION: "8"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn run test

build: off

branches:
  only:
    - master

deploy_script:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (yarn run prebuild && yarn run prebuild:upload -u %PREBUILD_UPLOAD%)
