[package]
name = "tree-sitter-commonlisp"
description = "Common Lisp grammar for the tree-sitter parsing library"
version = "0.2.0"
keywords = ["incremental", "parsing", "lisp", "common lisp"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
edition = "2018"
authors = ["Stephan Seitz"]
license = "GPLv3"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.19.5"

[build-dependencies]
cc = "1.0"
