name: Build/test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-2019]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test C stack code
        run: gcc test/test-stack.c -o a.out && ./a.out

      - name: Generate and check parser
        if: matrix.os == 'ubuntu-20.04'
        run: |
          npm install && npm run build
          git diff --quiet || (echo "::error file=grammar.js::Generated parser differs from the checked in version" && exit 1)

      - name: Parser tests 
        shell: bash
        run: npm install && npm run test
