name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Node versions
        run: |
          node --version
          npm --version
      - name: Install
        run: npm install
      - name: Test
        run: make generate test
  publish:
    name: Publish playground
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install
        run: npm install
      - name: Build
        run: make build-wasm
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: docs # The branch the action should deploy to.
          CLEAN: false # Automatically remove deleted files from the deploy branchs
          FOLDER: . # The folder the action should deploy.

